### ISSUE TITLE
VSCP_TYPE_INFORMATION_PROXIMITY_DETECTED - Zone/Sub-zone missing

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp-doc-spec#7]
Hi Ake,
could we keep the first three bytes of VSCP_TYPE_INFORMATION_PROXIMITY_DETECTED equal to the others, especially for zone/sub-zone. This makes it easier in the decision matrix for any CLASS1.INFORMATION event.

Bests
Andi

**Comment by grodansparadis** [comment]
You are right. Fixed.
