### ISSUE TITLE
Enhancement of Globally Unique Identifiers GUID section

### ISSUE THREAD

**Issue by michpro** [grodansparadis/vscp-doc-spec#9]
Please add, in the “Globally Unique Identifiers GUID” section, “manufacturer code” = 8 for GigaDevice Semiconductor. Their cheap ARM-core processor families, such as the GD32F10x, GD32F30x or GD32E50x, or the RISC-V-core GD32VF10x (which has a built-in CAN controller) have a unique 96-bit identifier, which is similar to the STM32 identifier.

**Comment by grodansparadis** [comment]
Have assigned manufacturer code = 8 for GigaDevice Semiconductor in v1.14.15.   
Thanks!
